### ISSUE TITLE
allow running tests on the installed version

### ISSUE THREAD

**Issue by daira** [PyCQA/modernize#12]
Since the tests directory isn't installed, it's not easy to run tests on the installed version.

If it is installed then it should probably be in `libmodernize.tests` rather than a toplevel module, to avoid module name clashes.

**Comment by graingert** [comment]
tox with pytest-cov is now configured to run the tests on the installed package:

https://github.com/PyCQA/modernize/blob/6b2a20089c786c9bdb03af5684cf7e5a8e90583a/setup.cfg#L67-L77
