### ISSUE TITLE
switch to flit (and one package)

### ISSUE THREAD

**Issue by graingert** [PyCQA/modernize#217]
> Currently it's impossible to distribute multiple modules/packages with flit.

I'd like to move everything under the `modernize` name and use `modernize/__main__.py`

**Comment by graingert** [comment]
@takluyver ^

**Comment by takluyver** [comment]
Be aware that the `libmodernize` name is exposed for selecting fixers (`python-modernize -f libmodernize.fixes.fix_open`), so moving everything to `modernize` could break scripts.

**Comment by graingert** [comment]
@takluyver we could hack it so modernize depended on a pypi libmodernize shim, but I think releasing v1 and documenting the breakage makes most sense?

**Comment by takluyver** [comment]
Your call. I think we made it so that the short names work as well (`python-modernize -f open`), so people have an easy way to avoid relying on the package name. But I'm sure something will break.

**Comment by graingert** [comment]
@takluyver I can release this in 0.9 as a semver breaking change. I've only been using the short names

**Comment by takluyver** [comment]
Up to you. It's bound to break something, somewhere, but maybe not much stuff, and I'm sure plenty of people are using modernize without pinning it to ensure a strictly semver-compatible version. But it's nothing people can't cope with.
