### ISSUE TITLE
Fix `unicode()` to `six.text_type()`

### ISSUE THREAD

**Issue by brettcannon** [PyCQA/modernize#39]
The idea is that regardless of what str/bytes strategy is chosen, you still need to replace calls to the `unicode()` type since `unicode` doesn't exist in Python 3. `six.text_type()` acts as a replacement since it is `unicode()` in Python 2 and `str()` in Python 3.

https://github.com/python-modernize/python-modernize/pull/38 implements this fixer.

**Comment by eli-schwartz** [comment]
> (I don't think variable names shadowing `unicode` are likely to be common enough to worry about that.)

Actually this just caught me out on one codebase, which is passing unicode=True to the GNUTranslations class in the stdlib gettext module. :p 
The argument does not seem to exist for python3's version, so I guess this needs fixing regardless, but I was a bit surprised to see tests failing even on python2 while trying to call `t.install(six.text_type=True)`.
