### ISSUE TITLE
Add an exit status to flag whether any change was actually necessary

### ISSUE THREAD

**Issue by brettcannon** [PyCQA/modernize#84]
People in some pre-commit hook may want to run `python-modernize` over changed code and reject the commit if it would lead to an actual change. This would allow a code base to be ported and then force developers to actually code in a Python 2/3 compatible way instead of perpetually relying on tools to do it for them.

**Comment by graingert** [comment]
there's currently a flag: `--enforce` https://github.com/PyCQA/modernize/pull/147
